name: Poetry sample project
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get codebase
        uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry
      - name: Poetry build project
        run: poetry install
        