name: First setup
on: [workflow_dispatch, issues, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hi Aravinth. Nice to meet you!"
      - name: Get run metadata
        run: echo "${{ toJson(github) }}"
