name: Poetry sample project
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Poetry build project
        run: poetry install
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pytesting the project
        run: pytest