name: Poetry sample project
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get codebase
        uses: actions/checkout@v4
      - name: Check python version
        run: python --version
      - name: Check pip version
        run: pip --version
      - name: Check poetry version
        run: poetry --version
        